version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    command: /bin/zsh
