version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./:/app
      - ./credential.json:/credential.json:ro
    working_dir: /app
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credential.json
    ports:
      - 127.0.0.1:8100:${PORT}
    tty: true
