version: 1

formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(name)s:%(lineno)d - %(message)s"
  cloud_logging_formatter:
    class: src.logger.formatter.CloudLoggingFormatter

handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

  azure_handler:
    class: opencensus.ext.azure.log_exporter.AzureLogHandler
    level: DEBUG
    formatter: simple

loggers:
  src:
    level: DEBUG
  __main__:
    level: DEBUG

root:
  level: WARNING
  handlers: [console_handler, azure_handler]

disable_existing_loggers: False
